name: Update README

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://github.com/ManojGithub1.atom"
          readme_path: "./README.md"
          max_post_count: 5
          comment_tag_name: "activity"
          commit_message: "chore: update recent activity"